import { Metadata } from "next";
import { Jost, Marcellus } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
});
const marcellus = Marcellus({
  variable: "--font-marcellus",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${jost.variable} ${marcellus.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
